version: "3"
services:
  foundation-mariadb:
    image: mariadb:11.2.2
    container_name: foundation-db
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=Change123
      - MARIADB_USER=foundation-user
      - MARIADB_PASSWORD=Change123
      - MARIADB_DATABASE=DotnetFoundation
    volumes:
      - foundation-db-data:/var/lib/mysql
    restart: always

  foundation-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - foundation-mariadb
    image: foundation-backend:1.0
    container_name: foundation-api
    ports:
      - 5000:5000
    environment:
      - DOTNET_URLS=http://+:5000

volumes:
  foundation-db-data:
    driver: local
