name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: Build
        run: |
          cd DotnetFoundation
          dotnet build --configuration Release
      - name: Test
        run: |
          cd DotnetFoundation
          dotnet test --configuration Release --no-build
